/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pink.digitally.games.whot;

public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
